### ISSUE TITLE
Unrecognized ResponseType

### ISSUE THREAD

**Issue by HazedSPaCEx** [Francesco149/sharenix#10]
Alright i have been trying to get the response type to work for sometime now but it keeps say the same think 'Unrecognized ResponseType'. 
This is what my config is: 
           {
            "Name": "Upload",
            "RequestType": "POST",
	    "Headers": {
                "Token": "my token"
            },
            "RequestURL": "my url",
            "FileFormName": "file",
            "ResponseType": "JSON",
            "URL": "$json:data.url$",
            "DeletionURL": ""
        },
And this is what my server sends back: 
res.type('json')
          var data = JSON.stringify({"status": 200,"data": {"url": "myurl"+name}});
          res.send(data)

**Comment by HazedSPaCEx** [comment]
Changed it to Text and it worked :man_shrugging: so yea

**Comment by Francesco149** [comment]
yes, response type is always Text. I think shareX is like that as well

**Comment by Francesco149** [comment]
(except for redirects)
