### ISSUE TITLE
Notifications are shown on the wrong display with a multi-display setup

### ISSUE THREAD

**Issue by ohyou** [Francesco149/sharenix#11]
Current behavior:
- When running `sharenix -n file.png`, the notification is shown on the right-most display in the bottom right corner

Expected behavior:
- When running `sharenix -n file.png`, the notification should be shown on the primary display in the bottom right corner

Specs:
- `Linux ou 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux`
- Dual monitor setup with primary display being the left-most one

Additional info:
I assume this happens because you simply take the "width" of the entire accessible area without considering the fact that it could be split between different physical monitors.
It would make sense to show notifications on the primary display.

**Comment by Francesco149** [comment]
interesting, I guess I never noticed the issue because my multi monitor setup has the rightmost one as the main. I will check that when I can

**Comment by Francesco149** [comment]
you can now set your preferred monitor index with this setting (tested on a dual monitor xinerama setup)  https://github.com/Francesco149/sharenix/blob/master/sharenix.json#L5
