### ISSUE TITLE
ShareNix: Request failed: (jsonpath not found)

### ISSUE THREAD

**Issue by RileyGuy** [Francesco149/sharenix#14]
It just randomly started doing this and I'm not sure what to do, I downloaded the latest version and it's still doing it. I've installed it using the instructions to a tee.

**Comment by Francesco149** [comment]
yes, it's a problem with imgur api. not sure what is happening but it just stopped working. switch the image uploader to hnng.moe or anything you like for now, ill let you know when it's fixed

**Comment by Francesco149** [comment]
seems like it was just a temporary imgur api outage of some sort, it works now!
