### ISSUE TITLE
[Help] Nextcloud/ownCloud integration

### ISSUE THREAD

**Issue by ReekyMarko** [Francesco149/sharenix#17]
What's the easiest way to get a base config for Nextloud image uploads? I tried to install ShareX to my Windows PC and export it from there but the exported file was a binary file. I also looked at ShareX's source code and it seems it's using WebDAV for the uploads, but with my limited knowledge, I was unable to create a configuration for sharenix. Any help would be greatly appreciated 😃

**Comment by Francesco149** [comment]
from a quick look at the api it will require
- support for PUT method
- support for basic http credentials
- your credentials will probably be in plaintext in the json until I have some kind of credentials storing method

anyways I'll try to implement it and we'll see

**Comment by ReekyMarko** [comment]
Aah thanks a lot!

**Comment by Francesco149** [comment]
done, here's an example that uploads to the demo owncloud. binaries coming soon...

https://github.com/Francesco149/sharenix/blob/master/sharenix.json#L44

**Comment by Francesco149** [comment]
released https://github.com/Francesco149/sharenix/releases/tag/0.9.7a

**Comment by ReekyMarko** [comment]
Amazing stuff! Thanks a bunch :blush:

**Comment by ReekyMarko** [comment]
Amazing stuff! Thanks a bunch :blush:
