### ISSUE TITLE
the clipboard store delay causes the notification to lock up

### ISSUE THREAD

**Issue by Francesco149** [Francesco149/sharenix#19]
I knew this was gonna happen.

https://github.com/Francesco149/sharenix/commit/b0ca5d20b578fe993f966d1b34717e2f15a87796 - since I force the gtk main loop to run for ~100ms it sometimes (often) runs out of events and hangs until I paste or open clipmenu, preventing the notification from showing

gotta find a nice way to confirm that the clipboard has been stored...

**Comment by discoli** [comment]
Was just going to create an issue about this, maybe just creating a ding sound or something configurable.

**Comment by Francesco149** [comment]
i ended up removing the waiting loop unless no notification is requested. this way it doesn't lock up with notifications
