### ISSUE TITLE
Clipboard clears after paste?

### ISSUE THREAD

**Issue by CLNinja** [Francesco149/sharenix#20]
Why does the clipboard clear after every paste? I'd prefer it not to.

**Comment by Francesco149** [comment]
huh, i've never had such issues. are you sure you have a clipboard manager? without a clipboard manager, the clipboard will be gone as soon as the notification disappears, that's just how it works on linux

the simplest clipboard manager I know of is parcellite, but many DEs already come with one

**Comment by CLNinja** [comment]
I currently have xclip installed. Copy + pasting from things like firefox and discord work properly.

**Comment by Francesco149** [comment]
xclip won't do. that's just a command line interface to put and get stuff from the clipboard.

on X, the clipboard stuff is held by the application that puts stuff into it, so unless there's a clipboard daemon running in the background constantly, the clipboard will disappear as soon as the application who filled it dies.

for example, if you copy some stuff in firefox, kill firefox and try to paste it will be gone

install parcellite and put

```
parcellite &
```
in your xinitrc before the line that starts i3

you can also manually start it from dmenu and such

if you need more power, such as browsing the clipboard history, you can use something like clipmenu, which I use on dwm https://github.com/cdown/clipmenu

**Comment by CLNinja** [comment]
Okay cool! Got that figured out. Thanks!
