### ISSUE TITLE
OCR Option

### ISSUE THREAD

**Issue by discoli** [Francesco149/sharenix#22]
Was just doing my homework, and had to translate English into Spanish, so I wanted to use OCR since copying is disabled, it'd be cool if you could run Sharenix in OCR mode and have it copy the text to keyboard.

There's probably a Go library for it, that'd be cool :)

**Comment by Francesco149** [comment]
I could do this using gosseract, but it feels like pulling in a huge library for a niche feature.

anyways I'll try it when I have time and let you know

**Comment by discoli** [comment]
Yeah, that's understandable, is a bit of a niche feature.

**Comment by Francesco149** [comment]
necropost but, I think this is better suited for a plugin rather than integrating it into sharenix. so closing this issue
