### ISSUE TITLE
-o cli flag not working properly?

### ISSUE THREAD

**Issue by Sphiinx** [Francesco149/sharenix#35]
I'm trying to test the -o flag through the cli by running the command "sharenix-section -o", but it doesn't seem to open the image in the browser after uploading the image. I'm using Firefox and it is set as my default browser.

Am I using the flag properly? I tried following the readme as best as possible.

**Comment by Francesco149** [comment]
ah right, the scripts don't forward args to sharenix, will have to fix that

**Comment by Sphiinx** [comment]
Sweet thanks!
