### ISSUE TITLE
Request failed: (jsonpath not found)

### ISSUE THREAD

**Issue by Sphiinx** [Francesco149/sharenix#36]
Anytime I try to take a screenshot, it fails to upload and says: "Request failed: (jsonpath not found".

This only started occurring recently and was working fine before?
![](https://i.imgur.com/PGa6MHT.png)

**Comment by Francesco149** [comment]
usually it's a temporary problem with imgur's api. at the moment it's working fine for me, is it still broken for you?

**Comment by Sphiinx** [comment]
@Francesco149 Yes it's still happening.

**Comment by Francesco149** [comment]
hmmmm i really don't know what it could be other than imgur api maybe blocking your ip for whatever reason.

this is the default config right? or do you have a custom config for imgur?

**Comment by Sphiinx** [comment]
@Francesco149 I seemed to have fixed the issue.

I created a new Bearer token for Imgur and set that to be the token. I'm not sure why the original one stopped working considering it was only a couple days old.
