### ISSUE TITLE
Site not found: default when -m=s

### ISSUE THREAD

**Issue by changchichung** [Francesco149/sharenix#39]
when I try to capture screen by selection area
always shows "Site not found: default"

```
2019-06-20 15:13:30 [changch@hqdc034 ~]$ sharenix -m=s 
Site not found: default
2019-06-20 15:13:41 [changch@hqdc034 ~]$ 
```
but full screen capture works fine.
```
2019-06-20 15:15:04 [changch@hqdc034 ~]$ sharenix -m=fs
Taking screenshot...
Uploading to imgur.com
URL: https://i.imgur.com/aaaaaaa.png
Deletion URL: https://imgur.com/delete/aaaaaaaaa
2019-06-20 15:15:24 [changch@hqdc034 ~]$ 
```
any suggestions ?

**Comment by Francesco149** [comment]
m=s is not implemented, use ```sharenix-section```

**Comment by changchichung** [comment]
yeah , I noticed that m=s is not implemented , but sharenix-section does not support editing after capture. hope the next version will be able to use the section , thanks !
