### ISSUE TITLE
sharenix-section 

### ISSUE THREAD

**Issue by elwolf6** [Francesco149/sharenix#40]
Gtk-CRITICAL **: 12:03:42.868: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

invalid character '\n' in string literal

Here is my sharenix.json

{
  "DefaultFileUploader": "Feen.us - elwolf6",
  "DefaultImageUploader": "Feen.us - elwolf6",
  "DefaultUrlShortener": "Feen.us - elwolf6,
  "XineramaHead": 0,
  "NotificationTime": 30,
  "NotifyUploading": true,
  "NotifyCommand": "",
  "ClipboardTime": 5,
  "SaveFolder": "sharenix",
  "OrganizedFolders": false,

  "Services": [
  	{
  	    "Name": "Feen.us - elwolf6",
  	    "DestinationType": "ImageUploader, TextUploader, FileUploader",
  	    "RequestType": "POST",
  	    "RequestURL": "https://feen.us/upload.php",
  	    "FileFormName": "d",
  	    "Arguments": {
  		  "secret": "stuff here i cant give out"
  	    },
  	    "ResponseType": "Text",
  	    "URL": "$json:file$"
  	}
  ]
}

**Comment by Francesco149** [comment]
I think this might be caused by semi-invalid json output from that sharing service, such as in this issue https://github.com/h2non/baloo/issues/14

I will take a better look later, can you provide example json output from an upload response?

**Comment by Francesco149** [comment]
you can enable debug output and get the raw http response by running ```sharenix-section -g``` by the way

**Comment by Francesco149** [comment]
I have no way of debugging this as I can't create a feen.us account myself. if you end up getting some debug output i can look at reopen.
