### ISSUE TITLE
QOL -- Move sharenix configuration to ~/.config/sharenix

### ISSUE THREAD

**Issue by zQueal** [Francesco149/sharenix#41]
This is a no-brainer. Sharenix configuration files under `~/sharenix` should be in `~/.config/sharenix`. 

For one, so they're hidden, and two so sharenix conforms to linux standards.

**Comment by Francesco149** [comment]
yeah at some point it would be neater to move archive to ~/.local/… and config to ~/.config/…

though some users might actually like the visibility of the archive folder for example people trying to find it with a graphical file manager

**Comment by zQueal** [comment]
> though some users might actually like the visibility

Then it would be prudent to make the paths configurable, and set the default to the linux standard which is hidden folders.

As it stands I've already found another solution that doesn't force non-hidden folders, so it's no longer an issue for me--but in the grand scheme of things following current standards is important.
