### ISSUE TITLE
Help converting config to sharenix

### ISSUE THREAD

**Issue by ducky710** [Francesco149/sharenix#48]
Hey just wanted to say I'm really excited I found this project, we really needed some sort of solution for linux. Thanks for putting this together! That aside I'm struggling to adapt my sharex config for airlift. I've been trying to mimic the default configs but I keep getting this error. Could you help me adapt this config? Attached the .json below(viewable in browser)

Uploading file to airlift
URL: (jsonpath not found)
Request failed: (jsonpath not found)

https://cloud.duck.casa/f/bb5a4bbd1713472a9ed8/

**Comment by Francesco149** [comment]
`$filename$` is not implemented in sharenix. but using `$input$` should achieve the same thing. try that

**Comment by ducky710** [comment]
Hey so I tried that out and I thought that it worked. It gave me the url saying "uploaded!" but when i went to the url it tries to download a file called $input$

heres the current config

{
      "Version": "12.4.1",
      "Name": "airlift",
      "DestinationType": "ImageUploader, TextUploader, FileUploader",
      "RequestType": "POST",
      "RequestURL": "https://HOST/upload/file",
      "Headers": {
        "X-Airlift-Filename": "$input$",
        "X-Airlift-Password": "PASSWORD"
      },
      "FileFormName": "file",
      "ResponseType": "Text",
      "Body": "Binary",
      "URL": "https://$json:URL$"
    },

**Comment by Francesco149** [comment]
hmm I think i need to add replacement keywords to the headers.

**Comment by Francesco149** [comment]
i pushed a fix, let me know if that works with the latest version and if not reopen the issue
