### ISSUE TITLE
XINERAMA

### ISSUE THREAD

**Issue by NickTurner21** [Francesco149/sharenix#49]
So when im trying to upload i am getting this error
No extension named XINERAMA could be found on on the server.
This was working yesterday now today it has all of a sudden stopped working. Any suggestions?

**Comment by NickTurner21** [comment]
Forgot to put, i am on ubuntu 20.04
libxinerama-dev is installed

**Comment by NickTurner21** [comment]
anyone?

**Comment by Francesco149** [comment]
i tried to fix in the latest release. if it's still broken reopen the issue
