### ISSUE TITLE
Please change versioning format to a valid semantic version

### ISSUE THREAD

**Issue by zneix** [Francesco149/sharenix#55]
Versioning of Sharenix has been following semantic versioning format until `v0.2.1` after which you've started adding letters to program versions which made [pkg.go.dev](https://pkg.go.dev/github.com/francesco149/sharenix?tab=versions) (see the link) no longer follow version updates from GitHub which makes it impossible to get correct module dependencies with `go get github.com/Francesco149/sharenix` because it tries to fetch deprecated `conformal/gotk3/gdk` and some other things that seem to be ultra outdated by over 5 years!

Why?
I wanted to add support for go modules (which would make future development way easier) and PR that, then add some small changes to the project itself but in the current state `go get` command fails almost instantly and I am stuck - unable to develop. So please make a release `v0.12.1` or something similar, so we can resolve that issue. Thanks!

![pls have mercy](https://cdn.zneix.eu/joe5Wkf.png)

**Comment by Francesco149** [comment]
i wasnt really strictly sticking to semantic versioning, I kinda made it up, the a was there because I never ended up developing it to a point that I felt was more than alpha, but yeah ill remove it

**Comment by Francesco149** [comment]
ok i got it to work https://pkg.go.dev/github.com/francesco149/sharenix@v0.12.3
