### ISSUE TITLE
Issue building on manjaro/arch

### ISSUE THREAD

**Issue by KenwoodFox** [Francesco149/sharenix#62]
not sure what im doing wrong, any clues? 
```makepkg -si                                                                                  ─╯
==> Making package: sharenix-git r183.27d8fb0-1 (Sun 28 Feb 2021 03:28:57 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating sharenix git repo...
Fetching origin
==> Validating source files with md5sums...
    sharenix ... Skipped
==> Extracting sources...
  -> Creating working copy of sharenix git repo...
Switched to a new branch 'makepkg'
==> Starting prepare()...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
go: cannot find main module, but found .git/config in /media/NotLocalDisk/Documents/ShareNix/src/build/src/github.com/Francesco149/sharenix
        to create a module there, run:
        go mod init
==> ERROR: A failure occurred in build().
    Aborting...```

**Comment by MrMemoL** [comment]
hi I was having problems with building I tried the pre-builded version but it was the same. Download these and your problem should be solved.

`sudo pacman -S lib32-gtk2
sudo pacman -S lib32-libsm`
if building doesn't work after this use the pre-builded version

**Comment by KenwoodFox** [comment]
> hi I was having problems with building I tried the pre-builded version but it was the same. Download these and your problem should be solved.
> 
> `sudo pacman -S lib32-gtk2`
> `sudo pacman -S lib32-libsm`
> if building doesn't work after this use the pre-builded version

Sorry :c that did not work.
Not sure whats going on? Where can I find the prebuilt?

**Comment by janderedev** [comment]
I'm having the same issue when installing `sharenix-git` from the AUR.
Using the prebuilt binaries works.

> Not sure whats going on? Where can I find the prebuilt?

https://github.com/Francesco149/sharenix/blob/master/README.md#installing---prebuilt-binaries

**Comment by WillyPillow** [comment]
Setting the environment variable `GO111MODULE=off` for `go get` seems to fix it for me.

**Comment by MBR-0001** [comment]
The message changed to `install: cannot stat '/home/mbr/sharenix-git/src/build/bin/sharenix': No such file or directory` for me after the latest update

**Comment by Francesco149** [comment]
@zneix patched the pkgbuild to work again. it should be fine now

**Comment by MBR-0001** [comment]
can confirm, it is possible to build the package again

**Comment by zneix** [comment]
Yup, all works and the issue can be closed.
