### ISSUE TITLE
Macos Support

### ISSUE THREAD

**Issue by Daggy1234** [Francesco149/sharenix#63]
Was really interested, any plans on adding Macos Support?

**Comment by ghost** [comment]
This probably isn’t gonna happen since Francesco said that “the project is mostly in mainteinance mode”. Maybe try [Magiccap](https://github.com/MagicCap/MagicCap)

**Comment by daggy1234** [comment]
Oh sorry to bother. I'm not a huge fan of magiccap because it is an electron app that's extremely heavy on system resources

**Comment by ghost** [comment]
> Oh sorry to bother. I'm not a huge fan of magiccap because it is an electron app that's extremely heavy on system resources

Yea im not a fan of magiccap either, but i would also recommend checking out [Flameshot](https://github.com/flameshot-org/flameshot) as its a good screenshot/annotation tool for all platforms and are also [interested in adding support for custom uploaders](https://github.com/flameshot-org/flameshot/pull/955)
