### ISSUE TITLE
sharenix-section gives error

### ISSUE THREAD

**Issue by Euro-pol** [Francesco149/sharenix#72]
If i do sharenix pathtofile, it uploads correctly.
But if i use sharenix-section it gives me this error: 
`/home/pi/bin/sharenix-section: 52: /home/pi/bin/sharenix-section: sharenix: not found
`

**Comment by Euro-pol** [comment]
also happens with sharenix-window

**Comment by real-F-00** [comment]
the path should be `/usr/bin/sharenix-section:` unless you specified your system to save software in that directory

**Comment by Euro-pol** [comment]
> the path should be `/usr/bin/sharenix-section:` unless you specified your system to save software in that directory

thanks, i already solved it by using path-to-sharenix instead of sharenix itself
