### ISSUE TITLE
Simpler region/window screenshots using xfce4-screenshoter

### ISSUE THREAD

**Issue by iamale** [Francesco149/sharenix#8]
No script files, just one command:  `xfce4-screenshooter -r -o "sharenix -n"` for region, `xfce4-screenshooter -w -o "sharenix -n"` for window. Should be usable in any DE I guess.

**Comment by Francesco149** [comment]
I actually have alternate scripts that check for gnome-screenshot and fallback to scrot that I will add soon. I will also add xfce4-screenshotter as you suggested
